<?php

/**
 * @file
 * Contains site_api.module.
 */
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function site_api_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    $config_var = \Drupal::service('config.factory')->getEditable('mymodule.settings');
    $site_api_key = $config_var->get('siteapikey');
    if($site_api_key != '') {
      $api_value = $site_api_key;
    } else {
      $api_value = 'No API Key yet';
    }
          $form['api_key'] = array(
            '#type' => 'textfield',
            '#title' => t('Site API Key'),
            '#default_value' => $api_value,
          );
          $form['actions']['submit']['#value'] = t('Update Configuration');
          $form['actions']['submit']['#submit'][] = 'api_key_form_submit';
          return $form;
  }
}
/**
 * Custom form submit handler 
 */
function api_key_form_submit(array $form, FormStateInterface $form_state){
      $api_key = $form_state->getValue('api_key');
      $config = \Drupal::service('config.factory')->getEditable('mymodule.settings');
      $config->set('siteapikey', $api_key)
      ->save();
      $site_api_key = $config->get('siteapikey');
      drupal_set_message('The Api key is - '.$site_api_key);
}
